- hosts: dev
  become: True
  tasks:
    - name: Instala python pip
      apt:
        name: python3-pip
        state: present
    - name: Instala docker
      apt:
        name: docker
        state: present
    - name: Inicia docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Instalar docker-py 
      pip:
        name: docker-py
        state: present
    - name: Inicia el contenedor
      docker_container:
        name: ciscossj
        image: "ciscossj/ciscoapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080